---
- name: Installing Apache Server
  apt: name=apache2 state=present
  when: ansible_pkg_mgr == "apt"
  tags:
    - apache

- name: Installing Apache Server
  yum: name=httpd state=present
  when: ansible_pkg_mgr == "yum"
  tags:
    - apache

- name: Starting Apache Server
  service: name=httpd state=started enabled=yes
  when: ansible_pkg_mgr == "yum"
  tags:
    - apache
